# Generated by Django 5.1.6 on 2025-02-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoiteALunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
