# Generated by Django 5.1.6 on 2025-02-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLTsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBoiteALunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boitealunch',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='JLTsite.categorieboitealunch'),
        ),
    ]
