# Generated by Django 5.1.6 on 2025-08-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLTsite', '0002_cart_cartitem_category_contactsubmission_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image principale'),
        ),
    ]
