# Generated by Django 5.1.6 on 2025-02-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLTsite', '0002_categorieboitealunch_boitealunch_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitealunch',
            name='prix',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
