# Generated by Django 5.1.6 on 2025-08-14 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLTsite', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_phone_order',
            field=models.BooleanField(default=False, verbose_name='Commande téléphonique'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_source',
            field=models.CharField(choices=[('online', 'En ligne'), ('manual', 'Manuelle (téléphone/sur place)'), ('admin', 'Créée par admin')], default='online', max_length=20, verbose_name='Source de la commande'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='department',
            field=models.CharField(blank=True, choices=[('patisserie', 'Pâtisserie'), ('chaud', 'Cuisine Chaude'), ('sandwichs', 'Sandwichs'), ('boites', 'Boîtes à lunch'), ('salades', 'Salades'), ('dejeuners', 'Déjeuners'), ('bouchees', 'Bouchées'), ('autres', 'Autres')], max_length=20, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_prepared',
            field=models.BooleanField(default=False, verbose_name='Préparé'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Préparé le'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_prepared', to=settings.AUTH_USER_MODEL, verbose_name='Préparé par'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='KitchenProductionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de production')),
                ('department', models.CharField(choices=[('patisserie', 'Pâtisserie'), ('chaud', 'Cuisine Chaude'), ('sandwichs', 'Sandwichs'), ('boites', 'Boîtes à lunch'), ('salades', 'Salades'), ('dejeuners', 'Déjeuners'), ('bouchees', 'Bouchées'), ('autres', 'Autres')], max_length=20, verbose_name='Département')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note de production',
                'verbose_name_plural': 'Notes de production',
                'ordering': ['-date', 'department'],
            },
        ),
    ]
