# Generated by Django 5.1.6 on 2025-08-15 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLTsite', '0004_order_created_by_order_is_phone_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('category', models.CharField(choices=[('ustensiles', 'Ustensiles'), ('contenants', 'Contenants'), ('nappes', 'Nappes et serviettes'), ('decorations', 'Décorations'), ('equipements', 'Équipements'), ('condiments', 'Condiments et sauces'), ('boissons', 'Boissons'), ('autres', 'Autres')], max_length=50, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('unit', models.CharField(default='unité', max_length=50, verbose_name='Unité de mesure')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('min_stock', models.IntegerField(default=10, verbose_name='Stock minimum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Article d'inventaire",
                'verbose_name_plural': "Articles d'inventaire",
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField(default=1, verbose_name='Quantité nécessaire')),
                ('quantity_prepared', models.IntegerField(default=0, verbose_name='Quantité préparée')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Validé')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('has_issue', models.BooleanField(default=False, verbose_name='Problème signalé')),
                ('issue_description', models.TextField(blank=True, verbose_name='Description du problème')),
                ('order', models.IntegerField(default=0)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_items', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JLTsite.inventoryitem', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Élément de checklist',
                'verbose_name_plural': 'Éléments de checklist',
                'ordering': ['order', 'inventory_item__category', 'inventory_item__name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('corporate', 'Événement corporatif'), ('wedding', 'Mariage'), ('cocktail', 'Cocktail'), ('lunch', 'Lunch box'), ('other', 'Autre')], max_length=50, verbose_name="Type d'événement")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modèle de checklist',
                'verbose_name_plural': 'Modèles de checklist',
                'ordering': ['event_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JLTsite.checklisttemplate')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JLTsite.inventoryitem')),
            ],
            options={
                'verbose_name': 'Item de modèle',
                'verbose_name_plural': 'Items de modèle',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='items',
            field=models.ManyToManyField(related_name='templates', through='JLTsite.ChecklistTemplateItem', to='JLTsite.inventoryitem'),
        ),
        migrations.CreateModel(
            name='OrderChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Complétée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0, verbose_name='Priorité (0=normale, 1=haute)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Assignée à')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='JLTsite.order')),
            ],
            options={
                'verbose_name': 'Checklist de commande',
                'verbose_name_plural': 'Checklists de commandes',
                'ordering': ['-priority', 'order__delivery_date', 'order__delivery_time'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('issue', 'Problème'), ('completed', 'Complétée'), ('urgent', 'Urgent'), ('info', 'Information')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JLTsite.checklistitem')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='JLTsite.orderchecklist')),
            ],
            options={
                'verbose_name': 'Notification de checklist',
                'verbose_name_plural': 'Notifications de checklist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='JLTsite.orderchecklist'),
        ),
    ]
