# Generated by Django 5.1.6 on 2025-08-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JLTsite', '0005_inventoryitem_checklistitem_checklisttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Client'), ('staff', 'Personnel'), ('admin', 'Administrateur'), ('checklist_manager', 'Checklist')], default='customer', max_length=20),
        ),
    ]
